- index.html
Updating the Banner to May, FAQ changes to follow with next larger update.
> Update To May

- index.html
Changes submitted by the web design team.
> Changed date and quarter to reflect new launch date.

- lib/metronome-auction-status-js/es5.js
- lib/metronome-auction-status-js/index.js
- package-lock.json
- package.json
- patches/shrink-array+0.0.2.patch
- src/components/MetPriceAreaBar.js
- src/components/TokenSaleCountdown.js
- src/reducers/auction.js
- Better/complete build script
- Fixes to the site for time < ISA start
> Final tweaks and fixes before launch

- src/components/GeneralStats.js
And clean up commented out code too.
> Remove market cap from dashboard

- package-lock.json
- package.json
- src/components/AuctionBuyForm.js
After sending a tx, all details are retrieved from the nodes. The request can be made to a different node than the one receiving the tx so the response might be `null`. The operation shall be retried in that case.
> Retry get tx detail

- config-overrides.js
Reapply reverted #44 into `staging`.
> Fix GA tag id injection

- public/apps/index.html
- public/auction/index.html
- public/dashboard/index.html
- public/privacy/index.html
Was missing from the new pages. Also adds missing Auction link in Privacy page.
> Fix OM link in the header

- lib/smart-round/es5.js
- lib/smart-round/index.js
- package-lock.json
- package.json
- src/components/EthValue.js
- src/components/FiatValue.js
- src/components/MetValue.js
The smartRounder is now smarter and is able to format the results in accounting format with thousand separators.
> Format values in accounting format

- src/components/MetPriceAreaBar.js
- src/css/styles.less
> Dashboard chart updates to show bars

- public/apps/index.html
- public/auction/index.html
- public/dashboard/index.html
- public/features/index.html
- public/index.html
- public/media-kit/index.html
- public/press/index.html
- public/press/launch-date-set/index.html
- public/privacy/index.html
This is a simple typo fix that needs to go live asap.
> Fix incorrect characters for Japanse in nav.

- src/components/AuctionBuyForm.js
This change will reduce significantly the chances of not being able to 
obtain the tx details.
> Better receipt flow

- src/components/GeneralStats.js
- src/components/MetPriceAreaBar.js
- src/components/pages/HomePage.js
- src/reducers/auction.js
As this is no longer needed after the ISA ended.
> Remove conditional ISA code

- src/css/styles.less
This improves tooltips typography font weight
> Fix CSS typo

- src/components/AuctionTokens.js
- src/components/GeneralStats.js
- Fix dashboard header margins and responsive bahavior
- Styling tweaks for "Available tokens" progress bar
Fixes #108
> Fix dashboard header margins and responsive bahavior

- src/components/AuctionSummary.js
- src/components/HeaderDashboard.js
- src/components/MetPriceAreaBar.js
> Clarify auction price and countdown texts according to auction status

- src/components/AuctionStatCard.js
- src/components/ConverterStatCard.js
- src/components/MainDashboard.js
- src/components/StatCard.js
> Add price charts to dashboard

- src/components/AuctionBuyForm.js
- src/components/AuctionPanel.js
- src/components/ChainWarning.js
- src/index.js
- src/providers/WalletInfo.js
> Add a warning banner when MetaMask is pointing to the wrong chain

- src/components/AuctionBuyForm.js
Too much cleanup in previous PR. This line was required.
> Reverts removed line

- src/analytics.js
- src/components/AuctionBuyForm.js
- src/index.js
> Send custom eventos to Google Analytics for Buy Met actions

- src/components/EthValue.js
- src/components/pages/AuctionPage.js
> Fix auction status loading

- src/create-store.js
> Disable localstorage Redux store enhancer while in development mode

- public/engage/index.html
- public/engage/sendmail.php
Redirect updated to relative path
> sendmail-redirect-update

- public/apps/index.html
- public/auction/index.html
- public/dashboard/index.html
- public/engage/index.html
- public/features/index.html
- public/index.html
- public/media-kit/index.html
- public/press/index.html
- public/privacy/index.html
- public/thank-you/index.html
We've updated the footer attribution link to correspond with our new organization, The Grove
> Footer Attribution Link

- public/apps/index.html
- public/auction/index.html
- public/dashboard/index.html
- public/engage/index.html
- public/features/index.html
- public/index.html
- public/media-kit/index.html
- public/thank-you/index.html
Footer update for Twitter link. 
Timeline update to Q2.
> Footer & timeline update

- public/index.html
The Grove - Timeline Update per Jordan
> timeline update

- public/about/index.html
- public/auction/index.html
- public/build/index.html
- public/buy/index.html
- public/converter/index.html
- public/dashboard/index.html
- public/engage/index.html
- public/index.html
- public/privacy/index.html
- public/roadmap/index.html
- public/thank-you/index.html
- public/wallet/index.html
Text edits on:
- Home
- Buy
- Build
- Engage
- Wallet
- Roadmap
> Content updates - multiple pages

- public/engage/index.html
> Engage page typo

- README.md
- config-overrides.js
- public/engage/index.html
> Make engage form URL configurable

- src/hocs/withProviderPermission.js
> Disable MM auto-refresh and set listener

- config-overrides.js
Until the mailer is operational, there should be no change in the site's behavior.
> Restore original sendmail behavior.

- .travis.yml
- src/components/auction/Receipt.js
- src/components/converter/Receipt.js
Fixes a typo and changes Travis config to deploy to both AWS S3 and GitHub Releases.
> Push minor fixes to prod

- .travis.yml
Adds a specific build distribution.
Add the `acl: public_read`
`max-age` not currently configured to be honored by cloudfront so removing.
> Some changes to Travis config

- .travis.yml
Bringing this up to date with the changes made in my deploy-test
> Fixed some Travis config options

- .travis.yml
Changed the travis.yml file to use the Travis deploy custom script
instead of using the canned Travis S3 deploy on the master branch.
> Modified Travis for master branch.

- package-lock.json
- package.json
- public/MET.svg
- public/buy/index.html
- src/components/RegisterToken.js
- src/components/auction/Receipt.js
- src/components/common/ProviderInfo.js
- src/components/converter/ConvertEthForm.js
- src/components/converter/ConvertMetForm.js
- src/components/converter/ConvertToggle.js
- src/components/converter/Converter.js
- src/components/converter/Modal.js
- src/components/converter/Receipt.js
- src/components/converter/Waiting.js
- src/index.js
- src/providers/WalletInfo.js
- src/reducers/convertForm.js
- src/reducers/convertPanel.js
- src/reducers/wallet.js
Also register token on MetaMask on first load.
> Add convert MET feature

- src/components/RegisterToken.js
- src/providers/WalletInfo.js
Also, verify MetaMask chain matches config chain when fetching MET balance.
> Make MET token registration consider current address and chain

- src/components/auction/Auction.js
Updates media query to show image in desktop resolution.
> Updates auction process image media query

- src/components/RegisterToken.js
- src/hocs/withProviderPermission.js
Metamask deprecated some apis in latest version 8.x.x.
This PR is addressing any such changes.
> Update deprecated apis from Metamask

- public/index.html
- src-static/js/main.js
- src-static/scss/components/_pages.scss
This PR will deploy to prod:
- Display fixes for Safari (#241)
> Deploy 2020-09-14
